<?php

$badriSahaba = array(
    "	Muhammad ibn 'Abdillah	",
    "	Abu Bakar as-Siddiq	",
    "	Umar bin al-Khattab	",
    "	Uthman bin Affan	",
    "	Ali bin Abu Talib	",
    "	Talhah bin ‘Ubaidillah	",
    "	Bilal bin Rabah	",
    "	Hamzah bin Abdul Muttalib	",
    "	Abdullah bin Jahsyi	",
    "	Al-Zubair bin al-Awwam	",
    "	Mus’ab bin Umair bin Hashim	",
    "	Abdur Rahman bin ‘Auf	",
    "	Abdullah bin Mas’ud	",
    "	Sa’ad bin Abi Waqqas	",
    "	Abu Kabshah al-Farisi	",
    "	Anasah al-Habsyi	",
    "	Zaid bin Harithah al-Kalbi	",
    "	Marthad bin Abi Marthad al-Ghanawi	",
    "	Abu Marthad al-Ghanawi	",
    "	Al-Husain bin al-Harith bin Abdul Muttalib	",
    "	‘Ubaidah bin al-Harith bin Abdul Muttalib	",
    "	Al-Tufail bin al-Harith bin Abdul Muttalib	",
    "	Mistah bin Usasah bin ‘Ubbad bin Abdul Muttalib	",
    "	Abu Huzaifah bin ‘Utbah bin Rabi’ah	",
    "	Subaih (servant of Abi ‘Asi bin Umayyah)	",
    "	Salim (servant of Abu Huzaifah)	",
    "	Sinan bin Muhsin	",
    "	‘Ukasyah bin Muhsin	",
    "	Sinan bin Abi Sinan	",
    "	Abu Sinan bin Muhsin	",
    "	Syuja’ bin Wahab	",
    "	‘Utbah bin Wahab	",
    "	Yazid bin Ruqais	",
    "	Muhriz bin Nadhlah	",
    "	Rabi’ah bin Aksam	",
    "	Thaqfu bin Amir	",
    "	Malik bin Amir	",
    "	Mudlij bin Amir	",
    "	Abu Makhsyi Suwaid bin Makhsyi al-Ta’i	",
    "	‘Utbah bin Ghazwan	",
    "	Khabbab (servant of ‘Utbah bin Ghazwan)	",
    "	Hathib bin Abi Balta’ah al-Lakhmi	",
    "	Sa’ad al-Kalbi (servant of Hathib)	",
    "	Suwaibit bin Sa’ad bin Harmalah	",
    "	Umair bin Abi Waqqas	",
    "	Al-Miqdad bin ‘Amru	",
    "	Mas’ud bin Rabi’ah	",
    "	Zus Syimalain Amru bin Amru	",
    "	Khabbab bin al-Arat al-Tamimi	",
    "	Amir bin Fuhairah	",
    "	Suhaib bin Sinan	",
    "	Abu Salamah bin Abdul Asad	",
    "	Syammas bin Uthman	",
    "	Al-Arqam bin Abi al-Arqam	",
    "	Ammar bin Yasir	",
    "	Mu’attib bin ‘Auf al-Khuza’i	",
    "	Zaid bin al-Khattab	",
    "	Amru bin Suraqah	",
    "	Abdullah bin Suraqah	",
    "	Sa’id bin Zaid bin Amru	",
    "	Mihja bin Akk (servant of Umar bin al-Khattab)	",
    "	Waqid bin Abdullah al-Tamimi	",
    "	Khauli bin Abi Khauli al-Ijli	",
    "	Malik bin Abi Khauli al-Ijli	",
    "	Amir bin Rabi’ah	",
    "	Amir bin al-Bukair	",
    "	Aqil bin al-Bukair	",
    "	Khalid bin al-Bukair	",
    "	Iyas bin al-Bukair	",
    "	Uthman bin Maz’un	",
    "	Qudamah bin Maz’un	",
    "	Abdullah bin Maz’un	",
    "	Al-Saib bin Uthman bin Maz’un	",
    "	Ma’mar bin al-Harith	",
    "	Khunais bin Huzafah	",
    "	Abu Sabrah bin Abi Ruhm	",
    "	Abdullah bin Makhramah	",
    "	Abdullah bin Suhail bin Amru	",
    "	Wahab bin Sa’ad bin Abi Sarah	",
    "	Hatib bin Amru	",
    "	Umair bin Auf	",
    "	Sa’ad bin Khaulah	",
    "	Abu Ubaidah Amir al-Jarah	",
    "	Amru bin al-Harith	",
    "	Suhail bin Wahab bin Rabi’ah	",
    "	Safwan bin Wahab	",
    "	Amru bin Abi Sarah bin Rabi’ah	",
    "	Sa’ad bin Muaz	",
    "	Amru bin Muaz	",
    "	Al-Harith bin Aus	",
    "	Al-Harith bin Anas	",
    "	Sa’ad bin Zaid bin Malik	",
    "	Salamah bin Salamah bin Waqsyi	",
    "	‘Ubbad bin Waqsyi	",
    "	Salamah bin Thabit bin Waqsyi	",
    "	Rafi’ bin Yazid bin Kurz	",
    "	Al-Harith bin Khazamah bin ‘Adi	",
    "	Muhammad bin Maslamah al-Khazraj	",
    "	Salamah bin Aslam bin Harisy	",
    "	Abul Haitham bin al-Tayyihan	",
    "	‘Ubaid bin Tayyihan	",
    "	Abdullah bin Sahl	",
    "	Qatadah bin Nu’man bin Zaid	",
    "	Ubaid bin Aus	",
    "	Nasr bin al-Harith bin ‘Abd	",
    "	Mu’attib bin ‘Ubaid	",
    "	Abdullah bin Tariq al-Ba’lawi	",
    "	Mas’ud bin Sa’ad	",
    "	Abu Absi Jabr bin Amru	",
    "	Abu Burdah Hani’ bin Niyyar al-Ba’lawi	",
    "	Asim bin Thabit bin Abi al-Aqlah	",
    "	Mu’attib bin Qusyair bin Mulail	",
    "	Abu Mulail bin al-Az’ar bin Zaid	",
    "	Umair bin Mab’ad bin al-Az’ar	",
    "	Sahl bin Hunaif bin Wahib	",
    "	Abu Lubabah Basyir bin Abdul Munzir	",
    "	Mubasyir bin Abdul Munzir	",
    "	Rifa’ah bin Abdul Munzir	",
    "	Sa’ad bin ‘Ubaid bin al-Nu’man	",
    "	‘Uwaim bin Sa’dah bin ‘Aisy	",
    "	Rafi’ bin Anjadah	",
    "	‘Ubaidah bin Abi ‘Ubaid	",
    "	Tha’labah bin Hatib	",
    "	Unais bin Qatadah bin Rabi’ah	",
    "	Ma’ni bin Adi al-Ba’lawi	",
    "	Thabit bin Akhram al-Ba’lawi	",
    "	Zaid bin Aslam bin Tha’labah al-Ba’lawi	",
    "	Rib’ie bin Rafi’ al-Ba’lawi	",
    "	Asim bin Adi al-Ba’lawi	",
    "	Jubr bin ‘Atik	",
    "	Malik bin Numailah al-Muzani	",
    "	Al-Nu’man bin ‘Asr al-Ba’lawi	",
    "	Abdullah bin Jubair	",
    "	Asim bin Qais bin Thabit	",
    "	Abu Dhayyah bin Thabit bin al-Nu’man	",
    "	Abu Hayyah bin Thabit bin al-Nu’man	",
    "	Salim bin Amir bin Thabit	",
    "	Al-Harith bin al-Nu’man bin Umayyah	",
    "	Khawwat bin Jubair bin al-Nu’man	",
    "	Al-Munzir bin Muhammad bin ‘Uqbah	",
    "	Abu ‘Uqail bin Abdullah bin Tha’labah	",
    "	Sa’ad bin Khaithamah	",
    "	Munzir bin Qudamah bin Arfajah	",
    "	Tamim (servant of Sa’ad bin Khaithamah)	",
    "	Al-Harith bin Arfajah	",
    "	Kharijah bin Zaid bin Abi Zuhair	",
    "	Sa’ad bin al-Rabi’ bin Amru	",
    "	Abdullah bin Rawahah	",
    "	Khallad bin Suwaid bin Tha’labah	",
    "	Basyir bin Sa’ad bin Tha’labah	",
    "	Sima’ bin Sa’ad bin Tha’labah	",
    "	Subai bin Qais bin ‘Isyah	",
    "	‘Ubbad bin Qais bin ‘Isyah	",
    "	Abdullah bin Abbas	",
    "	Yazid bin al-Harith bin Qais	",
    "	Khubaib bin Isaf bin ‘Atabah	",
    "	Abdullah bin Zaid bin Tha’labah	",
    "	Huraith bin Zaid bin Tha’labah	",
    "	Sufyan bin Bisyr bin Amru	",
    "	Tamim bin Ya’ar bin Qais	",
    "	Abdullah bin Umair	",
    "	Zaid bin al-Marini bin Qais	",
    "	Abdullah bin ‘Urfutah	",
    "	Abdullah bin Rabi’ bin Qais	",
    "	Abdullah bin Abdullah bin Ubai	",
    "	Aus bin Khauli bin Abdullah	",
    "	Zaid bin Wadi’ah bin Amru	",
    "	‘Uqbah bin Wahab bin Kaladah	",
    "	Rifa’ah bin Amru bin Amru bin Zaid	",
    "	Amir bin Salamah	",
    "	Abu Khamishah Ma’bad bin Ubbad	",
    "	Amir bin al-Bukair	",
    "	Naufal bin Abdullah bin Nadhlah	",
    "	‘Utban bin Malik bin Amru bin al-Ajlan	",
    "	‘Ubadah bin al-Somit	",
    "	Aus bin al-Somit	",
    "	Al-Nu’man bin Malik bin Tha’labah	",
    "	Thabit bin Huzal bin Amru bin Qarbus	",
    "	Malik bin Dukhsyum bin Mirdhakhah	",
    "	Al-Rabi’ bin Iyas bin Amru bin Ghanam	",
    "	Waraqah bin Iyas bin Ghanam	",
    "	Amru bin Iyas	",
    "	Al-Mujazzar bin Ziyad bin Amru	",
    "	‘Ubadah bin al-Khasykhasy	",
    "	Nahhab bin Tha’labah bin Khazamah	",
    "	Abdullah bin Tha’labah bin Khazamah	",
    "	Utbah bin Rabi’ah al-Khazraji	",
    "	Abu Dujanah Sima’ bin Kharasyah	",
    "	Al-Munzir bin Amru bin Khunais	",
    "	Abu Usaid bin Malik bin Rabi’ah	",
    "	Malik bin Mas’ud bin al-Badan	",
    "	Abu Rabbihi bin Haqqi bin Aus	",
    "	Ka’ab bin Humar al-Juhani	",
    "	Dhamrah bin Amru	",
    "	Ziyad bin Amru	",
    "	Basbas bin Amru	",
    "	Abdullah bin Amir al-Ba’lawi	",
    "	Khirasy bin al-Shimmah bin Amru	",
    "	Al-Hubab bin al-Munzir bin al-Jamuh	",
    "	Umair bin al-Humam bin al-Jamuh	",
    "	Tamim (servant of Khirasy bin al-Shimmah)	",
    "	Abdullah bin Amru bin Haram	",
    "	Muaz bin Amru bin al-Jamuh	",
    "	Mu’awwiz bin Amru bin al-Jamuh	",
    "	Khallad bin Amru bin al-Jamuh	",
    "	‘Uqbah bin Amir bin Nabi bin Zaid	",
    "	Hubaib bin Aswad	",
    "	Thabit bin al-Jiz’i	",
    "	Umair bin al-Harith bin Labdah	",
    "	Basyir bin al-Barra’ bin Ma’mur	",
    "	Al-Tufail bin al-Nu’man bin Khansa’	",
    "	Sinan bin Saifi bin Sakhr bin Khansa’	",
    "	Abdullah bin al-Jaddi bin Qais	",
    "	Atabah bin Abdullah bin Sakhr	",
    "	Jabbar bin Umaiyah bin Sakhr	",
    "	Kharijah bin Humayyir al-Asyja’i	",
    "	Abdullah bin Humayyir al-Asyja’i	",
    "	Yazid bin al-Munzir bin Sahr	",
    "	Ma’qil bin al-Munzir bin Sahr	",
    "	Abdullah bin al-Nu’man bin Baldumah	",
    "	Al-Dhahlak bin Harithah bin Zaid	",
    "	Sawad bin Razni bin Zaid	",
    "	Ma’bad bin Qais bin Sakhr bin Haram	",
    "	Abdullah bin Qais bin Sakhr bin Haram	",
    "	Abdullah bin Abdi Manaf	",
    "	Jabir bin Abdullah bin Riab	",
    "	Khulaidah bin Qais bin al-Nu’man	",
    "	An-Nu’man bin Yasar	",
    "	Abu al-Munzir Yazid bin Amir	",
    "	Qutbah bin Amir bin Hadidah	",
    "	Sulaim bin Amru bin Hadidah	",
    "	Antarah (servant of Qutbah bin Amir)	",
    "	Abbas bin Amir bin Adi	",
    "	Abul Yasar Ka’ab bin Amru bin Abbad	",
    "	Sahl bin Qais bin Abi Ka’ab bin al-Qais	",
    "	Amru bin Talqi bin Zaid bin Umaiyah	",
    "	Muaz bin Jabal bin Amru bin Aus	",
    "	Qais bin Mihshan bin Khalid	",
    "	Abu Khalid al-Harith bin Qais bin Khalid	",
    "	Jubair bin Iyas bin Khalid	",
    "	Abu Ubadah Sa’ad bin Uthman	",
    "	‘Uqbah bin Uthman bin Khaladah	",
    "	Ubadah bin Qais bin Amir bin Khalid	",
    "	As’ad bin Yazid bin al-Fakih	",
    "	Al-Fakih bin Bisyr	",
    "	Zakwan bin Abdu Qais bin Khaladah	",
    "	Muaz bin Ma’ish bin Qais bin Khaladah	",
    "	Aiz bin Ma’ish bin Qais bin Khaladah	",
    "	Mas’ud bin Qais bin Khaladah	",
    "	Rifa’ah bin Rafi’ bin al-Ajalan	",
    "	Khallad bin Rafi’ bin al-Ajalan	",
    "	Ubaid bin Yazid bin Amir bin al-Ajalan	",
    "	Ziyad bin Lubaid bin Tha’labah	",
    "	Khalid bin Qais bin al-Ajalan	",
    "	Rujailah bin Tha’labah bin Khalid	",
    "	Atiyyah bin Nuwairah bin Amir	",
    "	Khalifah bin Adi bin Amru	",
    "	Rafi’ bin al-Mu’alla bin Luzan	",
    "	Abu Ayyub bin Khalid al-Ansari	",
    "	Thabit bin Khalid bin al-Nu’man	",
    "	‘Umarah bin Hazmi bin Zaid	",
    "	Suraqah bin Ka’ab bin Abdul Uzza	",
    "	Suhail bin Rafi’ bin Abi Amru	",
    "	Adi bin Abi al-Zaghba’ al-Juhani	",
    "	Mas’ud bin Aus bin Zaid	",
    "	Abu Khuzaimah bin Aus bin Zaid	",
    "	Rafi’ bin al-Harith bin Sawad bin Zaid	",
    "	Auf bin al-Harith bin Rifa’ah	",
    "	Mu’awwaz bin al-Harith bin Rifa’ah	",
    "	Muaz bin al-Harith bin Rifa’ah	",
    "	An-Nu’man bin Amru bin Rifa’ah	",
    "	Abdullah bin Qais bin Khalid	",
    "	Wadi’ah bin Amru al-Juhani	",
    "	Ishmah al-Asyja’i	",
    "	Thabit bin Amru bin Zaid bin Adi	",
    "	Sahl bin ‘Atik bin al-Nu’man	",
    "	Tha’labah bin Amru bin Mihshan	",
    "	Al-Harith bin al-Shimmah bin Amru	",
    "	Ubai bin Ka’ab bin Qais	",
    "	Anas bin Muaz bin Anas bin Qais	",
    "	Aus bin Thabit bin al-Munzir bin Haram	",
    "	Abu Syeikh bin Ubai bin Thabit	",
    "	Abu Tolhah bin Zaid bin Sahl	",
    "	Abu Syeikh Ubai bin Thabit	",
    "	Harithah bin Suraqah bin al-Harith	",
    "	Amru bin Tha’labah bin Wahb bin Adi	",
    "	Salit bin Qais bin Amru bin ‘Atik	",
    "	Abu Salit bin Usairah bin Amru	",
    "	Thabit bin Khansa’ bin Amru bin Malik	",
    "	Amir bin Umaiyyah bin Zaid	",
    "	Muhriz bin Amir bin Malik	",
    "	Sawad bin Ghaziyyah	",
    "	Abu Zaid Qais bin Sakan	",
    "	Abul A’war bin al-Harith bin Zalim	",
    "	Sulaim bin Milhan	",
    "	Haram bin Milhan	",
    "	Qais bin Abi Sha’sha’ah	",
    "	Abdullah bin Ka’ab bin Amru	",
    "	‘Ishmah al-Asadi	",
    "	Abu Daud Umair bin Amir bin Malik	",
    "	Suraqah bin Amru bin ‘Atiyyah	",
    "	Qais bin Mukhallad bin Tha’labah	",
    "	Al-Nu’man bin Abdi Amru bin Mas’ud	",
    "	Al-Dhahhak bin Abdi Amru	",
    "	Sulaim bin al-Harith bin Tha’labah	",
    "	Jabir bin Khalid bin Mas’ud	",
    "	Sa’ad bin Suhail bin Abdul Asyhal	",
    "	Ka’ab bin Zaid bin Qais	",
    "	Bujir bin Abi Bujir al-Abbasi	",
    "	‘Itban bin Malik bin Amru al-Ajalan	",
    "	‘Ismah bin al-Hushain bin Wabarah	",
    "	Hilal bin al-Mu’alla al-Khazraj	",
    "	Awleh bin Syuqrat (assistant of Muhammad)	",


); ?>







<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>






    <div class="container">
        <h1>List Of Badr Sahaba Names Participated In Ghazwa Badr</h1>
        <table class="table table-dark table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Names</th>

                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($badriSahaba as $index => $itemsNames) {
                    echo "<tr>";
                    echo "<td>" . $index + 1 . "</td>";
                    echo "<td>" . $itemsNames . "</td>";
                    echo "</tr>";
                }
                ?>
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>